following_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    detection_timeout: 5.0
    linear_tolerance: 0.15
    angular_tolerance: 0.15
    max_retries: 3
    base_frame: "base_link"
    fixed_frame: "odom"
    allow_backward: true
    desired_distance: 1.0
    skip_orientation: true
    filter_coef: 0.1
    controller:
      k_phi: 1.0
      k_delta: 2.0
      beta: 0.4
      lambda: 2.0
      v_linear_min: 0.1
      v_linear_max: 1.0
      v_angular_max: 2.0
      slowdown_radius: 0.15
      use_collision_detection: true
      costmap_topic: "local_costmap/costmap_raw"
      footprint_topic: "local_costmap/published_footprint"
      transform_tolerance: 0.5
      projection_time: 5.0
      simulation_time_step: 0.1
      dock_collision_threshold: 0.0